[font]
size = 13.0

[font.normal]
family = "Maple Mono SC NF"
style = "Regular"

[font.bold]
family = "Maple Mono SC NF"
style = "Bold"

[font.italic]
family = "Maple Mono SC NF"
style = "Italic"

[font.bold_italic]
family = "Maple Mono SC NF"
style = "Bold Italic"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15
