_installSymbolicLink alacritty ~/.config/alacritty ~/.local/dotfiles/config/alacritty/ ~/.config
_installSymbolicLink gitconfig ~/.gitconfig ~/.local/dotfiles/config/git/.gitconfig ~/.gitconfig
_installSymbolicLink fontconfig ~/.config/fontconfig ~/.local/dotfiles/config/fontconfig/ ~/.config
_installSymbolicLink starship ~/.config/starship.toml ~/.local/dotfiles/config/starship/pastel-powerline.toml ~/.config/starship.toml
_installSymbolicLink nvimPlugin ~/.config/nvim/lua/plugins ~/.local/dotfiles/config/nvim/lua/plugins/ ~/.config/nvim/lua
_installSymbolicLink nvimConfig ~/.config/nvim/lua/config ~/.local/dotfiles/config/nvim/lua/config/ ~/.config/nvim/lua
_installSymbolicLink nvimCustomLib ~/.config/nvim/lua/customLib ~/.local/dotfiles/config/nvim/lua/customLib/ ~/.config/nvim/lua
_installSymbolicLink nvimTemplates ~/.config/nvim-templates ~/.local/dotfiles/config/nvim-templates/ ~/.config
_installSymbolicLink nvimSpell ~/.config/nvim/spell ~/.local/dotfiles/config/nvim-spell/ ~/.config/nvim
