format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#DA627D"
format = "[ $path ]($style)on "
truncation_length = 1
truncation_symbol = "…/"

[character]
success_symbol = "[❯](#fa29c0)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
symbol = ""
format = "[ $symbol $branch ]($style)"
style = "#6090e6"

[git_status]
style = "#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
